TARGETS=read_console send_drive_data test_axi

HEADERS=
SOURCES=

INTF_HEADERS=../interface/rcci_client.h ../interface/rcci_type.h
INTF_SOURCES=../interface/rcci_client.cpp

THIS_DIR:=$(dir $(abspath $(lastword $(MAKEFILE_LIST))))

include ../Makefile.core
